---

resources:
resources:
- name: every-30s
  type: time
  icon: clock-outline
  source:
    interval: 30s


jobs:
- name: hello-world
  public: true
  plan:
  - get: every-30s
    trigger: true
  - task: print-hello-world
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: busybox }
      run:
        path: echo
        args: ["Hello world!"]
